### ISSUE TITLE
Character Jump

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#13]
Players need the ability to jump so that they can dodge attacks and move through the environment. If players press and hold the jump button, the player should jump double the height of the character. If the button is pressed without holding the character it's own height. If the button is tapped the character should jump 50% of it's own height.
- [ ] Implement functionality to recognize if a button is held.
- [ ] Implement functionality to recognize if a button is pressed.
- [ ] Implement functionality to recognize if a button is tapped.

**Comment by truepaddii** [comment]
Need additional info about the timing. How long does it take the system to recognize a press event / tap event / hold event?

**Comment by truepaddii** [comment]
We need an input system to implement this properly. The player can jump so do we need this right now?
