### ISSUE TITLE
Character Shoot

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#15]
As a player I need the ability to shoot a laser to damage objects and the enemy. 

- [x] Spawn laser that damages enemies
- [ ] ~~Aiming over the right twinstick~~

**Comment by truepaddii** [comment]
**Needs a split** Shots mechanically are a bullets system and the logic of aiming is another system. Please specify atomically.

**Comment by Helero** [comment]
please specify what you mean. Do you want it devided into 2 cards or do you want more specification in the task list ? and what do you mean with "atomically" ?

**Comment by ProducerPhil** [comment]
I think he just meant more specification, "on an atomical level" is just an exaggeration. But for easier understanding include every little detail for the mechanic you want.

We have another issue regarding the aiming, I changed this issue here accordingly.
