### ISSUE TITLE
Boss Mechanik 5 - Spear

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#21]
The Boss has a Spear which he can hit the Player with.
Allows him to summon more Spears at the top of the Screen which fall down and damage the player if he is not standing under a platform. This mechanic is going to make the Player leave the top platform, which is the only platform from which the player can reach the head.

[180605141931.mp4](https://app.gitkraken.com/api/glo/boards/5af1a5f8c9b0cf0e008cdcb4/attachments/5b167fa04f33b715001b7cb5)
 

description is still unfinished pls wait for update
- [x] spawn lances
- [x] timer that indicates how long the lances hang at the top of the screen until they fall down _as variable_
- [x] lances damage the player

**Comment by truepaddii** [comment]
Future feature cards that are not written in English will be marked as invalid.

**Comment by truepaddii** [comment]
soon on WIP branch

**Comment by truepaddii** [comment]
Engine ready in commit e61a20ab81e3c2af4b205710cc3cbab2423168bb
