### ISSUE TITLE
Boss Mechanik 6 - Fireball

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#22]
Base Boss Attack. -> probably needs updating because of Lance Overhead Slash!

~~basis attacke vom boss. bringt den spieler dazu seine fähigkeiten zu nutzen und nicht dauerhaft auf der gleichen stelle stehen zu bleiben~~ 

- [x] Spawn point for projectile
- [x] projectile does damage on player on contact (damage as **variable**)
- [x] ~~wenn der ball eine wand trift splittet er sich in 3 bälle auf und bounced von der wand ab wieder zurück (diese bälle fügen dem spieler ebenfals schaden zu für dedails siehe decription)~~

- [x] Projectile is cast on last player position

[180605133823.mp4](https://app.gitkraken.com/api/glo/boards/5af1a5f8c9b0cf0e008cdcb4/attachments/5b1676dcc9b0cf0e0093cfa8)

**Comment by Helero** [comment]
i did that so this one is done for gate 1 but need rework for gate 2

**Comment by truepaddii** [comment]
Future feature cards that are not written in English will be marked as invalid.
