### ISSUE TITLE
Boss mechanic 9 - Shield _ object

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#29]
challanges the player that he can not shoot everything so he has to be carefull and to evaluate when it is smart to shoot and when not.
- [x] object that reflects the players laser (angle of incidence is equal to the angle of reflection)
- [x] object that circles around the boss

**Comment by truepaddii** [comment]
This has been implemented and commited in (mirror effect) ccadb2b81f5c6de56e3241ba42071230e14de9f8 and in e8196fdbba79dddb64a378ee256b425ca18a538d (rotation)
