### ISSUE TITLE
Environment Tiles - Art

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#30]
Tiles that are needed for basic level design

- [x] wall tiles middle
- [x] wall tiles upper end
- [x] wall tiles lower end
- [x] Destroiable wall tiles (normal wall tiles with cracks)
- [x] middle ground tiles
- [x] right end side ground tiles
- [x] left end side ground tiles
- [ ] Stairway tiles
- [x] Platform tiles
- [x] Book case tiles upper end
- [x] Book case tiles lower end
- [x] Book case tile middle

**Comment by ProducerPhil** [comment]
The stairways shouldn't actually be 80x80 pixel blocks which need to be jumped up.
The player should be able to simply run up the stairs. 
I will create an issue for the programmers.
