### ISSUE TITLE
Player Is Shrinking

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#33]
ragardless wich size the player has they always shrink to the sice 0.65 xyz when the play button is pressed

**Comment by truepaddii** [comment]
**Please stick to English**

**Comment by truepaddii** [comment]
Cannot reproduce this issue. Maybe you're setting it in play mode? Try setting the value inside the editor before starting play mode.

**Comment by truepaddii** [comment]
**Solved** removed the code in commit 7ed082460a8c5c2b1785831f3cbb529d6d965328
