### ISSUE TITLE
boss phase system

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#38]
triggers differend phases depending on remaning hp of the boss
- [ ] trigger to change phases depending on remaining boss hp

**Comment by truepaddii** [comment]
**Need Info**: What are boss phases? What is a trigger in this sense? Is the system only dependent on the health of the parent object or can it change? Does a "state" have multiple behaviours from which a random choice is made, for instance, can an attack vary within a state? What variables do you need for the balancing?

**Comment by Helero** [comment]
the boss phases are the diferent attakes from the player as well as combinations of two or three of those.
it is dependend on the boss hp meaning it is an open variable for example at 50 hp left trigger mechanik1  or at 20 hp left trigger mechanic 2 and 3
no variables there the boss is scriptet meaning he will always do that exact attack when the hp is at that number 
i need a variable for hp number at wich something is trigerd, a variable for what it is that is triggered
