### ISSUE TITLE
Player receives damage

### ISSUE THREAD

**Issue by ProducerPhil** [ProjectMansionManiac/MansionMadness#48]
Player shall receive damage when

- [x] collider player and collider boss collide
- [ ] ~~player gets hit by the bosses Lance Overhead Slash~~
- [x] player gets hit by Projectile
- [x] player gets hit by bosses Lance Charge
- [x] player gets hit by Lance Rain Projectiles

Then, the player shall
- [x] be pushed back a little (knockback as variable)
- [x] knockback can be turned on and off in unity (for game design purpos)
- [x] receive a certain amount of damage (amount of damage as variable)
- [x] have a short time of invincibility after getting hit

**Comment by truepaddii** [comment]
This script could be used by other static assets as well that deal damage and knoch the player back.

**Comment by ProducerPhil** [comment]
True dat. Would actually go well with every kind of damage the player receives. I'll edit it accordingly.

**Comment by truepaddii** [comment]
I don't think, it's a good thing that the player receives a knockback on damage.

**Comment by truepaddii** [comment]
Already in the build. The player is damaged and is knocked back when receiving damage.
