### ISSUE TITLE
Boss Phase Tool

### ISSUE THREAD

**Issue by ProducerPhil** [ProjectMansionManiac/MansionMadness#51]
We need a tool to determine, which phase triggers when and what happens in that phase. 

Issue will be updated regularly!

- [x] Phase Selection
- [x] Phase triggers after _body part_ takes _amount of damage_
- [x] Selection what attacks are used in a phase

- [x] main boss hp only reduces when the head is hit

**Comment by truepaddii** [comment]
Review? Is it considered done?
