### ISSUE TITLE
After being reflected by a mirror once, laser does not reflect a second time and does no damage to boss

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#61]
steps to reproduce problem 1

1.shoot the laser towords the mirror 
2. wait for the laser to hit the mirror 
3.mirror reflekts the laser
4.laser goes in the direction of a other mirror
5.laser hits other mirror 
6.laser goes through second mirror

expectet result:
laser gets reflected by second mirror again 

actual result:
laser goes through the second mirror without hitting it at all

steps to reproduce problem 2

1.shoot the laser towords the mirror 
2. wait for the laser to hit the mirror 
3.mirror reflekts the laser
4.laser goes in the direction of the boss
5.laser stops at the hitbox of the boss
6.boss gets no damage animation
7.boss gets no damage

expectet result:
laser triggers the boss gets hurt animation 
laser reduces hp of the boss

actual result:
laser stops at the bosses hitbox but does no damage and damage animation

**Comment by truepaddii** [comment]
What happened here? This doesn't look like English.

**Comment by darktoastbrot** [comment]
fixed
