### ISSUE TITLE
Boss is turned away 180° from player in mirror phase

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#62]
der boss dreht sich immer vom spieler weg anstatt zum spieler hin. der fehöer liegt im mirrorphasen script 

result: Boss turns his back towards the player

expected result: should always face the player during the mirror phase

**Comment by truepaddii** [comment]
Future bug reports that are not written in English or have the wrong formatting will be marked as invalid as explained in #53
