### ISSUE TITLE
Jump height variable

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#63]
steps to reproduce problem 

1) press jump button
2) charakter jumps
3) change jump variable in player script in unity 
4) press jump button
5) character jumps
6) jump hight does not differ from 2)

expected result:
character jump height from 2 differs to 5

actual result:
character jump height from 2 and 5 does not differ from each other

**Comment by truepaddii** [comment]
Fixed in commit e61a20ab81e3c2af4b205710cc3cbab2423168bb
(Use velocity variables in player script which are now provided inside the editor)

**Comment by darktoastbrot** [comment]
fixed, can be edited in runtime now.
