### ISSUE TITLE
Ammo Refill Balancing Variable

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#79]
Stepps to reproduce Problem:

1.go into the unity Editor
2.hit Play
3. shoot with the Charakter while pressing rightstick and RB 
4.stopp Shooting
5. see how the amo meter in the left Corner of the Screen fills up again 
6.change value of Max amo, refil Tick,Current amo and refil amound in the edditor in the  Player Shooting script
7. repeat stepp 3-5 
8.compair how fast the amo refills in both cases 
9. see that it does not differ

expectet result:
value of Max amo, refil Tick,Current amo and refil amound Change somthing in the Shooting procedure

actual result:
the dont Change anything visible

other aproach for the same issue :

1.go into the unity Editor
2.hit Play
3. shoot with the Charakter while pressing rightstick and RB 
4.stopp Shooting
5. see how the amo meter in the left Corner of the Screen fills up again 
6. exit playmode
6.change value of Max amo, refil Tick,Current amo and refil amound in the edditor in the Player Shooting script
7. repeat stepp 2-6 
8.compair how fast the amo refills in both cases 
9. see that it does not differ

expectet result:
value of Max amo, refil Tick,Current amo and refil amound Change somthing in the Shooting procedure

actual result:
the dont Change anything visible

**Comment by darktoastbrot** [comment]
fixed
