### ISSUE TITLE
HP GUI bug

### ISSUE THREAD

**Issue by Helero** [ProjectMansionManiac/MansionMadness#89]
steps to reproduce issue:

1. go into the unity Editor and Change the Player hp to a number over 100
2.start the game and get damage
3. see that the heart in the left upper Corner of the Screen does not Change

what is expectet:
the heart gets smaller in % to the remaning hp

what is actually Happening:
the heart only gets smaller as soon as only 100 hp is left

**Comment by truepaddii** [comment]
Has been fixed in commit 6d59951ff38899206e30de7174d0d42acbb09a40
